    name: Particles
    main: me.cloyd1815.particles.ParticlesMain
    version: 0.1
    depend: [WorldEdit]
    description: Made by Sockmonkey
    commands:
      part:
        description: stuff!